### ISSUE TITLE
Regarding the classifier part of the paper, SDN reference code

### ISSUE THREAD

**Issue by wushupei1997** [PotatoTian/recall-semseg#1]
Hello, I would like to ask about the reference code of the SDN in the classification part of the paper. Can you share it?

**Comment by PotatoTian** [comment]
Hi,

Thank you for your interests. We do not have a plan to release the code for classification right now. Our method is primarily derived for segmentation, so we would like to keep this repo solely for this task. In later experiments, we discovered that the improvement mainly comes from the SDN architecture, not from Recall loss. We, therefore, removed the classification part in our new accepted version. We are open to research discussion on why SDN was helpful in this case. It seems that simple methods can achieve SoA performance as well.  Keep me posted on your experiments and results! 

Sincerely,
Junjiao
